env: "local"

http:
  address: ":80"
  timeout: 5s
  timeIdle: 60s

grpc:
  port: 50523

storage:
  host: postgres
  user: "dev"
  password: "dev"
  database: "dev"
  port: 5432

kafka:
  address: ["localhost:9001", "localhost:9002", "localhost:9003"]